CREATE TYPE "Direction" AS ENUM ('INCOME', 'EXPENSE');
CREATE TYPE "ExpenseNature" AS ENUM ('NECESSARY', 'OPTIONAL', 'UNCLASSIFIED');
CREATE TYPE "CategoryKind" AS ENUM ('INCOME', 'EXPENSE');
CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL, "userId" TEXT, "name" TEXT NOT NULL, "level" INTEGER NOT NULL DEFAULT 1, "kind" "CategoryKind" NOT NULL, "defaultExpenseNature" "ExpenseNature" NOT NULL DEFAULT 'UNCLASSIFIED', "sortOrder" INTEGER NOT NULL DEFAULT 0, "parentId" TEXT, CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Transaction" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "occurredOn" TEXT NOT NULL, "direction" "Direction" NOT NULL, "amountCents" INTEGER NOT NULL, "categoryId" TEXT, "merchant" TEXT, "note" TEXT, "expenseNature" "ExpenseNature" NOT NULL DEFAULT 'UNCLASSIFIED', "source" TEXT NOT NULL DEFAULT 'MANUAL', "sourceReference" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Budget" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "month" TEXT NOT NULL, "categoryId" TEXT NOT NULL, "amountCents" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Budget_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE INDEX "Category_userId_kind_idx" ON "Category"("userId", "kind"); CREATE INDEX "Transaction_userId_occurredOn_idx" ON "Transaction"("userId", "occurredOn"); CREATE INDEX "Transaction_userId_categoryId_idx" ON "Transaction"("userId", "categoryId"); CREATE UNIQUE INDEX "Budget_userId_month_categoryId_key" ON "Budget"("userId", "month", "categoryId");
ALTER TABLE "Category" ADD CONSTRAINT "Category_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Category" ADD CONSTRAINT "Category_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Budget" ADD CONSTRAINT "Budget_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
